### ISSUE TITLE
Failed to execute 'observe' on 'IntersectionObserver': parameter 1 is not of type 'Element'."

### ISSUE THREAD

**Issue by lenriquez** [maoberlehner/lazy-load-vue-components-when-they-become-visible#1]
Hello!
I am getting this error in this line `observer.observe(this.$el);` if I print  `this.$el ` I get a HTML comment. I am not sure what I am doing wrong, could you please help me with this 

Thank you for help

**Comment by maoberlehner** [comment]
Hi! Please use the following issue: https://github.com/maoberlehner/vue-lazy-hydration/issues/19 (at first glance this seems to be the same problem).

Please provide further information - ideally a link to reproduction on CodeSandbox. Thx!
